name: Build and deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  jekyll: # same name as file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GTIHUB_TOKEN }}